version: '3'

services:
  nginx:
    image: nginx:1.20-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./var/log:/var/log/nginx

  php:
    image: registry.gitlab.com/ng-workshops/ci/symfony:latest
    build:
      context: ./docker/php
    user: php
    env_file:
      - ./.env.docker.local
      - ./.env
    volumes:
      - .:/app
      - ~/.composer:/var/composer:cached

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgres_data: ~
