parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $cdnUrl: '%env(CDN_URL)%'
            $planets: '%planets%'
            $tmpStorageDir: '%tmp_storage_dir%'
            $astronautsStorageDir: '%astronauts_storage_dir%'
            $planetsStorageDir: '%planets_storage_dir%'
    App\:
        resource: '%kernel.project_dir%/src/'
        exclude:
            - '%kernel.project_dir%/src/DependencyInjection/'
            - '%kernel.project_dir%/src/Entity/'
            - '%kernel.project_dir%/src/Kernel.php'

    App\Controller\:
        resource: '%kernel.project_dir%/src/Controller/'
        tags:
            - controller.service_arguments
