services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
        bind:
            $baseUri: 'http://symfony.workshop-ci.local'
